### PR TITLE
To do list peer Review

### PR DESCRIPTION
**Pull request by Caren-Koroeny**
- Kindly feel free to Review my work according to the JS Best practice.
- Ensure to check for the quality of the code (you can use previous lessons as a guide). Remember to check for the following:
[JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
[DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) rules.
[HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### CODE REVIEW

**Comment by jkanyi-web** [comment]
I can't see any files on this repository and thus I am unable to make any issue

**Comment by Caren-Koroeny** [comment]
Go to pull request and comment on that pull request do not create an issue
thats not the exercise....but rather a conversation at the pull request.

**Comment by jkanyi-web** [comment]
Oh yeah I intended to say comment. You we're supposed to have files on this repository so that I can check the files and comment to make sure they code is in accordance with best practices. Or am I getting this whole exercise wrong?

**Comment by jkanyi-web** [comment]
Copy Paste ToDo list src files into this repository so that I can find something to comment on

**Comment by Caren-Koroeny** [comment]
- Sorry Kanyi, okay I know and understand why you can not review I will work on it today ASAP

**Comment by Caren-Koroeny** [comment]
Kindly feel free to check on it

**Comment by jkanyi-web** [comment]
No many needed changes but just to reduce and also increase readability, you can use a forEach method to loop through the items instead of the normal for loop on line 26 and line 34 of index.js. Otherwise very nice arrangement of code and functionality.

**Comment by Caren-Koroeny** [comment]
Okay Thank you

**Review by jkanyi-web — APPROVED** [review]

**Pull request merged**
